server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/ChenJie666/microservicecloud-config
          #uri:  git@github.com:ChenJie666/microservicecloud-config

#通过：
#http://config-3344.com:3344/application-dev.yml
#http://config-3344.com:3344/master/application-dev.yml
#http://config-3344.com:3344/application/dev/master
#进行访问